server:
  port: 8081

spring:
  application:
    name: MEMBERSERVICE
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/member?createDatabaseIfNotExist=true
    username: etlee
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


jwt:
  secret: 21bf4bbdab0d30e78c28f150a7cbf5f6f24fd19f635c2b43a8031d2ac6c67a6f
  accessTokenExpirationMs: 3600000  # 1 hour
  refreshTokenExpirationMs: 86400000 # 24 hour